name: Publish OrderData to Kafka in Quix
language: python
variables:
  - name: output_topic
    inputType: OutputTopic
    description: ''
    defaultValue: orders
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
