FROM localstack/localstack:latest

# Set environment variables
ENV SERVICES=kinesis
ENV AWS_ACCESS_KEY_ID=test
ENV AWS_SECRET_ACCESS_KEY=test
ENV AWS_DEFAULT_REGION=us-east-1

# Expose necessary ports
EXPOSE 4566

# Start LocalStack
CMD ["localstack", "start"]