name: transformation_lambda_replacement
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: orders
    required: false
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write to.
    defaultValue: orders_normalized
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
