name: Kinesis Source
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write into
    defaultValue: kinesis_data
    required: true
  - name: kinesis_stream
    inputType: FreeText
    description: ''
    defaultValue: kinesis_data
    required: false
  - name: aws_region_name
    inputType: FreeText
    description: ''
    defaultValue: us-east-1
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-source
