name: Publish OrderLineData to Kafka in Quix
language: python
variables:
  - name: output_topic
    inputType: OutputTopic
    description: ''
    defaultValue: orderlines
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
