name: Publish OrderLineData to Kafka in Quix
language: python
variables:
  - name: kinesis_stream_name_flink
    inputType: FreeText
    description: ''
    defaultValue: BenchmarkOrderlinesInputV1
    required: false
  - name: S3_BUCKET_NAME
    inputType: FreeText
    description: ''
    defaultValue: kinesis-benchmarking
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
