name: transformation_flink_replacement
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: orderlines
    required: false
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write to.
    defaultValue: 5min-product-counts
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
